# UNMANAGED, project-specific build wiring. This file is never regenerated by a
# template upgrade — it is the one place to evolve the package build and any
# custom checks.
#
# VARIANT A — kiroku carries its own nix/haskell-overlay.nix. Build from a
# ghc9124 package set extended with two composed overlays: the shared haskell-nix
# registry (patch management) composed with the project's ./nix/haskell-overlay.nix.
{ inputs, ... }:
{
  perSystem =
    { system, pkgs, ... }:
    let
      haskellPackages = pkgs.haskell.packages.ghc9124.override {
        overrides =
          pkgs.lib.composeExtensions (inputs.haskell-nix.lib.haskellExtension pkgs.haskell.lib.compose pkgs)
            (import ./nix/haskell-overlay.nix { inherit pkgs; });
      };
    in
    {
      packages = {
        kiroku-store = haskellPackages.kiroku-store;
        kiroku-store-migrations = haskellPackages.kiroku-store-migrations;
        shibuya-kiroku-adapter = haskellPackages.shibuya-kiroku-adapter;
        kiroku-otel = haskellPackages.kiroku-otel;
        kiroku-cli = haskellPackages.kiroku-cli;
        kiroku-metrics = haskellPackages.kiroku-metrics;
        default = haskellPackages.kiroku-store;
      };
    };
}
