module Kiroku.Store.Types (
    StreamName (..),
    StreamId (..),
    EventId (..),
    EventType (..),
    StreamVersion (..),
    GlobalPosition (..),
    ExpectedVersion (..),
    EventData (..),
    RecordedEvent (..),
    StreamInfo (..),
    AppendResult (..),
    LinkResult (..),
    CategoryName (..),
    categoryName,
    streamNameInCategory,
    EventFilter (..),
) where

import Data.Aeson (Value)
import Data.Int (Int64)
import Data.Text (Text)
import Data.Text qualified as Text
import Data.Time (UTCTime)
import Data.UUID (UUID)
import GHC.Generics (Generic)

-- Stream identification

{- | The human-readable name of a stream (e.g. @"orders-1"@). Stream names
are unique per store; the substring before the first @-@ is the
stream's category, used by 'CategoryName'-targeted reads and
subscriptions.

All names except @$all@ are ordinary application stream names. Names
such as @"invoice-payment"@, @"$invoice-payment"@, names containing
commas, and names without a dash are accepted by the store. The exact
name @$all@ is reserved for the global read stream and mutating APIs
reject it with 'Kiroku.Store.Error.ReservedStreamName'; use
'Kiroku.Store.Read.readAllForward' or
'Kiroku.Store.Read.readAllBackward' to read the global sequence.
-}
newtype StreamName = StreamName Text
    deriving stock (Eq, Ord, Show, Generic)

{- | The database surrogate id of a stream. Stable for the lifetime of
the stream row; reused by 'hardDeleteStream' followed by re-creation
only at the database's discretion. Not generally used by application
code — prefer 'StreamName' for identification.
-}
newtype StreamId = StreamId Int64
    deriving stock (Eq, Ord, Show, Generic)

-- Event identification

{- | The store's identifier for an event. Generated by the store as a
UUIDv7 unless the caller supplies one in 'EventData.eventId' (used for
idempotent retries — see 'appendToStream').

The 'Ord' instance compares by raw UUID byte order, /not/ by
generation time. UUIDv7 is timestamp-prefixed in its high bytes, so
byte order roughly matches generation order, but two ids generated in
the same millisecond can compare in either direction. For
time-ordering use 'RecordedEvent.globalPosition'.
-}
newtype EventId = EventId UUID
    deriving stock (Eq, Ord, Show, Generic)

{- | The application-level discriminator for an event payload (e.g.
@"OrderCreated"@). Free-form text; the store does not interpret it.
-}
newtype EventType = EventType Text
    deriving stock (Eq, Ord, Show, Generic)

-- Positions

{- | Monotonic per-stream version counter. Starts at 0 for a freshly
created empty stream and increments by one per appended event. After
@N@ events, the stream's version is @N@; the @i@-th event has
@streamVersion = i@ (one-indexed within a stream).
-}
newtype StreamVersion = StreamVersion Int64
    deriving stock (Eq, Ord, Show, Generic)

{- | Monotonic global position counter, shared across all streams.
Strictly increasing per successful append; gap-free under all four
'ExpectedVersion' paths (see EP-1's audit). Used by the @$all@ read
path and by subscriptions as the cursor key.
-}
newtype GlobalPosition = GlobalPosition Int64
    deriving stock (Eq, Ord, Show, Generic)

{- | Version expectations for appends.

The store enforces optimistic concurrency at the stream level: each
'appendToStream' call carries an 'ExpectedVersion' that the
@stream_version@ row must satisfy at commit time. A mismatch produces
'Kiroku.Store.Error.WrongExpectedVersion' or
'Kiroku.Store.Error.StreamAlreadyExists' depending on the constructor.
-}
data ExpectedVersion
    = {- | The stream must not exist yet. Creates the stream and appends
      the events. Fails with
      'Kiroku.Store.Error.StreamAlreadyExists' if the stream is
      already present, including soft-deleted streams. Use this for
      aggregate creation.
      -}
      NoStream
    | {- | The stream must already exist (and not be soft-deleted), but
      its current version does not matter. Fails with
      'Kiroku.Store.Error.StreamNotFound' if the stream is missing
      or soft-deleted.
      -}
      StreamExists
    | {- | The stream's current version must match exactly. Use this
      when the caller has read the stream and wants to append only
      if no concurrent writer has advanced it. Fails with
      'Kiroku.Store.Error.WrongExpectedVersion' on mismatch.
      -}
      ExactVersion !StreamVersion
    | {- | Upsert: create the stream if missing, append otherwise. Does
      not check the existing version. Maps to a single
      @INSERT ... ON CONFLICT DO UPDATE@ at the SQL layer. The name
      is historical — \"create-or-append\" is the working
      description.
      -}
      AnyVersion
    deriving stock (Eq, Show, Generic)

{- | What the caller provides when appending events.

Field accessors are intended to be used through @generic-lens@ labels
(@event ^. #eventType@); the cabal common stanza enables
@DuplicateRecordFields@ and @OverloadedLabels@ so the same field names
can appear on both 'EventData' and 'RecordedEvent'.
-}
data EventData = EventData
    { eventId :: !(Maybe EventId)
    {- ^ 'Nothing' lets the store generate a UUIDv7 at append time. 'Just'
    lets the caller supply an id, primarily to make appends idempotent
    across transient failures: a retry with the same id either succeeds
    (because the previous attempt did not commit) or surfaces as
    'Kiroku.Store.Error.DuplicateEvent' (because it did).
    -}
    , eventType :: !EventType
    {- ^ Application-level discriminator. Free-form; the store does not
    interpret it but it is indexed for queries.
    -}
    , payload :: !Value
    -- ^ The event's JSONB payload.
    , metadata :: !(Maybe Value)
    {- ^ Optional JSONB metadata. Often used for tenant ids, trace
    contexts, and correlation data.
    -}
    , causationId :: !(Maybe UUID)
    {- ^ Optional id of the event that caused this one (the immediate
    cause). Used to reconstruct chains.
    -}
    , correlationId :: !(Maybe UUID)
    {- ^ Optional correlation id (the saga / transaction this event
    belongs to). Distinct from @causationId@.
    -}
    }
    deriving stock (Show, Generic)

{- | Stream metadata returned by 'getStream'.

The 'id' field shadows 'Prelude.id' under 'DuplicateRecordFields'; access
it via @info ^. #id@ to disambiguate. 'Prelude.id' remains available as
@Data.Function.id@ if needed.
-}
data StreamInfo = StreamInfo
    { id :: !StreamId
    {- ^ The stream's database surrogate id. Stable for the row's
    lifetime.
    -}
    , name :: !StreamName
    -- ^ The stream's human-readable name as supplied at creation.
    , version :: !StreamVersion
    -- ^ The stream's current version (count of appended events).
    , createdAt :: !UTCTime
    -- ^ When the stream row was first inserted.
    , deletedAt :: !(Maybe UTCTime)
    {- ^ 'Just' the soft-delete timestamp if the stream has been
    soft-deleted, 'Nothing' otherwise. Hard-deleted streams do not
    appear in 'getStream' at all.
    -}
    }
    deriving stock (Eq, Show, Generic)

{- | What comes back from reading events.

For events read from their /source/ stream, @streamVersion@ and
@originalVersion@ agree, and @originalStreamId@ matches the stream being
read. For events read from a /linked/ target stream (one populated by
'linkToStream'), @streamVersion@ is the target's version (the position
of the link in the target stream) while @originalVersion@ is the
source's version (where the event lived when first appended) and
@originalStreamId@ is the source's id. Subscriptions and category reads
return events at their source positions.
-}
data RecordedEvent = RecordedEvent
    { eventId :: !EventId
    -- ^ The event's stable id (UUIDv7 by default).
    , eventType :: !EventType
    -- ^ The application-level type discriminator.
    , streamVersion :: !StreamVersion
    {- ^ Position in the stream being read. For source-stream reads this
    equals @originalVersion@; for linked-target reads it is the
    link's position in the target.
    -}
    , globalPosition :: !GlobalPosition
    {- ^ Position in the global @$all@ sequence at original-append time.
    Stable across links; used as the subscription cursor.
    -}
    , originalStreamId :: !StreamId
    {- ^ The surrogate id of the stream the event was first appended to. For
    fan-in reads (@$all@, categories, causation\/correlation queries,
    subscriptions) this is the only stream identifier on the event; resolve a
    batch of these to human-readable 'StreamName's with
    'Kiroku.Store.Read.lookupStreamNames'.
    -}
    , originalVersion :: !StreamVersion
    -- ^ The position the event was assigned in its source stream.
    , payload :: !Value
    , metadata :: !(Maybe Value)
    , causationId :: !(Maybe UUID)
    , correlationId :: !(Maybe UUID)
    , createdAt :: !UTCTime
    }
    deriving stock (Eq, Show, Generic)

-- | Result of a successful 'appendToStream' or 'appendMultiStream' call.
data AppendResult = AppendResult
    { streamId :: !StreamId
    {- ^ The id of the stream that was appended to (created if it did
    not exist).
    -}
    , streamVersion :: !StreamVersion
    {- ^ The stream's version after the append (the position of the
    /last/ event in the batch).
    -}
    , globalPosition :: !GlobalPosition
    -- ^ The global position assigned to the /last/ event in the batch.
    }
    deriving stock (Eq, Show, Generic)

{- | Result of a successful 'linkToStream' call.

There is no @globalPosition@ field because linking does not advance the
global counter — the linked events keep their original
'globalPosition'. To enumerate the new positions of linked events, read
the target stream after the call.
-}
data LinkResult = LinkResult
    { streamId :: !StreamId
    -- ^ The id of the link target (created if it did not exist).
    , streamVersion :: !StreamVersion
    {- ^ The target's version after the link (position of the /last/
    linked event in the target).
    -}
    }
    deriving stock (Eq, Show, Generic)

{- | The category prefix of a stream name (the part before the first
@-@). E.g., @StreamName "orders-1"@ has @CategoryName "orders"@. Used by
'readCategory' and category-targeted subscriptions to fan-in events from
many streams that share a prefix.
-}
newtype CategoryName = CategoryName Text
    deriving stock (Eq, Ord, Show, Generic)

{- | The category of a stream name: the substring before the first @-@. This
is the canonical Haskell mirror of the
@streams.category GENERATED ALWAYS AS split_part(stream_name,'-',1)@ column and
of the category rule used by 'Kiroku.Store.Read.readCategory' and
category-targeted subscriptions. A category never contains @-@, so this is
exact.

>>> categoryName (StreamName "orders-1")
CategoryName "orders"

A name without a dash is its own category:

>>> categoryName (StreamName "singleton")
CategoryName "singleton"
-}
categoryName :: StreamName -> CategoryName
categoryName (StreamName t) = CategoryName (Text.takeWhile (/= '-') t)

{- | Build the stream name for a category and an id segment, i.e.
@\<category\>-\<id\>@. The dual of 'categoryName': for any dash-free category,
@'categoryName' ('streamNameInCategory' cat seg) == cat@.

This is permissive — it does not reject a hyphenated 'CategoryName' or an empty
segment (the store accepts such names); opinionated validation is the caller's
concern.

>>> streamNameInCategory (CategoryName "orders") "1"
StreamName "orders-1"
-}
streamNameInCategory :: CategoryName -> Text -> StreamName
streamNameInCategory (CategoryName cat) seg = StreamName (cat <> "-" <> seg)

{- | Filter passed to the 'Kiroku.Store.Effect.FindEvents' constructor and the
public smart constructors in "Kiroku.Store.Causation". Each constructor maps
to one SQL statement in "Kiroku.Store.SQL".

The sum is closed: mock interpreters that implement 'Kiroku.Store.Effect.Store'
can pattern-match exhaustively. Adding a new filter is a breaking change for
downstream interpreters and is captured by GHC's exhaustiveness check.
-}
data EventFilter
    = -- | Match every event whose @correlation_id@ equals the supplied UUID.
      FilterCorrelation !UUID
    | {- | Match the seed event and every event whose @causation_id@ chain
      walks back to it. The seed event itself is included as the depth-0
      row when it exists.
      -}
      FilterCausationDescendants !EventId
    | {- | Match the seed event and every event reachable by walking
      @causation_id@ upward from the seed. The seed itself is included.
      -}
      FilterCausationAncestors !EventId
    deriving stock (Eq, Show, Generic)
