cabal-version: 3.0
name:          inspection-workload-gate
version:       0.1.0.0
build-type:    Simple

executable inspection-workload-gate
  main-is:            Main.hs
  hs-source-dirs:     .
  other-modules:      Kiroku.Test.Postgres
  default-language:   GHC2024
  default-extensions:
    DuplicateRecordFields
    NoFieldSelectors
    OverloadedLabels
    OverloadedRecordDot
    OverloadedStrings

  ghc-options:
    -O2 -threaded -rtsopts "-with-rtsopts=-N -A32m" -fproc-alignment=64

  build-depends:
    , aeson
    , base
    , generic-lens
    , hasql
    , hasql-pool
    , hasql-transaction
    , kiroku-store
    , kiroku-test-support
    , lens
    , process
    , tasty
    , tasty-bench
    , text
    , time
    , vector
